# Generated by Django 3.2.3 on 2021-05-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFund', '0002_alter_schemes_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemes',
            name='scheme_detail_info',
        ),
        migrations.RemoveField(
            model_name='schemes',
            name='scheme_short_info',
        ),
        migrations.AddField(
            model_name='schemes',
            name='scheme_details',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='schemes',
            name='scheme_info',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='scheme_code',
            field=models.CharField(default=True, max_length=6),
        ),
    ]
