# Generated by Django 3.2.3 on 2021-05-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFund', '0004_auto_20210530_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='scheme_details',
            field=models.JSONField(default=dict),
        ),
    ]
