# Generated by Django 3.2.3 on 2021-05-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFund', '0005_alter_scheme_scheme_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='scheme_code',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_info',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
