# Generated by Django 3.2.3 on 2021-05-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFund', '0003_auto_20210530_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_code', models.CharField(default=True, max_length=6)),
                ('scheme_info', models.CharField(default=True, max_length=250)),
                ('scheme_details', models.JSONField(default='{}')),
            ],
        ),
        migrations.DeleteModel(
            name='Schemes',
        ),
    ]
