# Generated by Django 3.2.3 on 2021-05-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFund', '0006_auto_20210530_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='scheme_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_info',
            field=models.CharField(default='', max_length=250),
        ),
    ]
