# Generated by Django 3.1.4 on 2021-05-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MFund', '0007_auto_20210530_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='scheme_details',
        ),
    ]
