# Generated by Django 3.2 on 2021-04-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreamApp', '0002_videos_vid_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
