# Generated by Django 3.2 on 2021-04-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StreamApp', '0004_rename_vid_name_video_video_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_obj', to='StreamApp.streamername'),
        ),
    ]
