# Generated by Django 3.2 on 2021-04-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreamApp', '0005_alter_video_vid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_type',
            new_name='vtype',
        ),
    ]
